wandb_version: 1

algorithm:
  value: DQN
alpha:
  value: 0.00018233459491189704
batch_size:
  value: 128
buffer_size:
  value: 10000
env:
  value: CartPole-v1
epsilon:
  value: 0.9625838245516916
gamma:
  value: 0.9572049570084552
learning_start:
  value: 1000
max_episode_steps:
  value: 1000
model_type:
  value: medium
num_envs:
  value: 8
save_test:
  value: 1000
tau:
  value: 1
total_time_steps:
  value: 100000
train_frequency:
  value: 10
update_target_frequency:
  value: 100
use_per:
  value: false
wandb_log:
  value: true
