wandb_version: 1

algorithm:
  value: DQN
alpha:
  value: 5.173159684674383e-05
batch_size:
  value: 512
buffer_size:
  value: 5000
env:
  value: CartPole-v1
epsilon:
  value: 0.98650495221638
gamma:
  value: 0.9508483313765012
learning_start:
  value: 3000
max_episode_steps:
  value: 1000
model_type:
  value: small
num_envs:
  value: 8
save_test:
  value: 1000
tau:
  value: 1
total_time_steps:
  value: 300000
train_frequency:
  value: 50
update_target_frequency:
  value: 100
use_per:
  value: false
wandb_log:
  value: true
