wandb_version: 1

algorithm:
  value: DQN
alpha:
  value: 0.0006446217581938834
batch_size:
  value: 256
buffer_size:
  value: 20000
env:
  value: CartPole-v1
epsilon:
  value: 0.9091194732540422
gamma:
  value: 0.9681438779241196
learning_start:
  value: 20000
max_episode_steps:
  value: 1000
model_type:
  value: small
num_envs:
  value: 8
save_test:
  value: 1000
tau:
  value: 1
total_time_steps:
  value: 2000000
train_frequency:
  value: 20
update_target_frequency:
  value: 100
use_per:
  value: false
wandb_log:
  value: true
