wandb_version: 1

algorithm:
  value: DQN
alpha:
  value: 2.261048834382047e-05
batch_size:
  value: 512
buffer_size:
  value: 10000
env:
  value: CartPole-v1
epsilon:
  value: 0.9316200294738304
gamma:
  value: 0.9434371982944976
learning_start:
  value: 2000
max_episode_steps:
  value: 1000
model_type:
  value: small
num_envs:
  value: 8
save_test:
  value: 1000
tau:
  value: 1
total_time_steps:
  value: 300000
train_frequency:
  value: 10
update_target_frequency:
  value: 500
use_per:
  value: false
wandb_log:
  value: true
