wandb_version: 1

algorithm:
  value: DQN
alpha:
  value: 0.0005550081268751269
batch_size:
  value: 512
buffer_size:
  value: 5000
env:
  value: CartPole-v1
epsilon:
  value: 0.9088730470747484
gamma:
  value: 0.9288608434950456
learning_start:
  value: 3000
max_episode_steps:
  value: 1000
model_type:
  value: medium
num_envs:
  value: 8
save_test:
  value: 1000
tau:
  value: 1
total_time_steps:
  value: 200000
train_frequency:
  value: 20
update_target_frequency:
  value: 100
use_per:
  value: false
wandb_log:
  value: true
