wandb_version: 1

algorithm:
  value: DQN
alpha:
  value: 0.00034519143615056305
batch_size:
  value: 128
buffer_size:
  value: 10000
env:
  value: CartPole-v1
epsilon:
  value: 0.9835232190139226
gamma:
  value: 0.9016498897669996
learning_start:
  value: 2000
max_episode_steps:
  value: 1000
model_type:
  value: small
num_envs:
  value: 8
save_test:
  value: 1000
tau:
  value: 1
total_time_steps:
  value: 200000
train_frequency:
  value: 50
update_target_frequency:
  value: 100
use_per:
  value: false
wandb_log:
  value: true
