wandb_version: 1

algorithm:
  value: DQN
alpha:
  value: 0.0006555144539470346
batch_size:
  value: 128
buffer_size:
  value: 5000
env:
  value: CartPole-v1
epsilon:
  value: 0.9330637244016232
gamma:
  value: 0.9711154146145228
learning_start:
  value: 3000
max_episode_steps:
  value: 1000
model_type:
  value: medium
num_envs:
  value: 8
save_test:
  value: 1000
tau:
  value: 1
total_time_steps:
  value: 200000
train_frequency:
  value: 10
update_target_frequency:
  value: 100
use_per:
  value: false
wandb_log:
  value: true
