wandb_version: 1

algorithm:
  value: DQN
alpha:
  value: 9.78760917089924e-05
batch_size:
  value: 128
buffer_size:
  value: 5000
env:
  value: CartPole-v1
epsilon:
  value: 0.9047240066292476
gamma:
  value: 0.9074480757518378
learning_start:
  value: 2000
max_episode_steps:
  value: 1000
model_type:
  value: large
num_envs:
  value: 8
save_test:
  value: 1000
tau:
  value: 1
total_time_steps:
  value: 100000
train_frequency:
  value: 10
update_target_frequency:
  value: 250
use_per:
  value: false
wandb_log:
  value: true
