wandb_version: 1

algorithm:
  value: DQN
alpha:
  value: 0.0004003723139419222
batch_size:
  value: 128
buffer_size:
  value: 10000
env:
  value: CartPole-v1
epsilon:
  value: 0.913248426585508
gamma:
  value: 0.9018957773297194
learning_start:
  value: 1000
max_episode_steps:
  value: 1000
model_type:
  value: large
num_envs:
  value: 8
save_test:
  value: 1000
tau:
  value: 1
total_time_steps:
  value: 300000
train_frequency:
  value: 20
update_target_frequency:
  value: 500
use_per:
  value: false
wandb_log:
  value: true
