wandb_version: 1

algorithm:
  value: DQN
alpha:
  value: 2.3182177572416534e-05
batch_size:
  value: 128
buffer_size:
  value: 10000
env:
  value: CartPole-v1
epsilon:
  value: 0.9629734940247466
gamma:
  value: 0.9552846602346644
learning_start:
  value: 1000
max_episode_steps:
  value: 1000
model_type:
  value: medium
num_envs:
  value: 8
save_test:
  value: 1000
tau:
  value: 1
total_time_steps:
  value: 200000
train_frequency:
  value: 10
update_target_frequency:
  value: 500
use_per:
  value: false
wandb_log:
  value: true
