wandb_version: 1

algorithm:
  value: DQN
alpha:
  value: 5.8104371507572384e-05
batch_size:
  value: 256
buffer_size:
  value: 5000
env:
  value: CartPole-v1
epsilon:
  value: 0.9055649581834044
gamma:
  value: 0.9243763466700512
learning_start:
  value: 1000
max_episode_steps:
  value: 1000
model_type:
  value: large
num_envs:
  value: 8
save_test:
  value: 1000
tau:
  value: 1
total_time_steps:
  value: 100000
train_frequency:
  value: 10
update_target_frequency:
  value: 100
use_per:
  value: false
wandb_log:
  value: true
