wandb_version: 1

algorithm:
  value: DQN
alpha:
  value: 0.0004476731730495051
batch_size:
  value: 256
buffer_size:
  value: 5000
env:
  value: CartPole-v1
epsilon:
  value: 0.9208105066018228
gamma:
  value: 0.9185515666208164
learning_start:
  value: 1000
max_episode_steps:
  value: 1000
model_type:
  value: medium
num_envs:
  value: 8
save_test:
  value: 1000
tau:
  value: 1
total_time_steps:
  value: 300000
train_frequency:
  value: 20
update_target_frequency:
  value: 250
use_per:
  value: false
wandb_log:
  value: true
