wandb_version: 1

algorithm:
  value: DQN
alpha:
  value: 0.00031624381081580465
batch_size:
  value: 256
buffer_size:
  value: 10000
env:
  value: CartPole-v1
epsilon:
  value: 0.9846339130301414
gamma:
  value: 0.9736372269138472
learning_start:
  value: 2000
max_episode_steps:
  value: 1000
model_type:
  value: small
num_envs:
  value: 8
save_test:
  value: 1000
tau:
  value: 1
total_time_steps:
  value: 300000
train_frequency:
  value: 50
update_target_frequency:
  value: 100
use_per:
  value: false
wandb_log:
  value: true
