wandb_version: 1

algorithm:
  value: DQN
alpha:
  value: 0.0006017276926500824
batch_size:
  value: 128
buffer_size:
  value: 10000
env:
  value: CartPole-v1
epsilon:
  value: 0.9836958365540924
gamma:
  value: 0.9857585773767978
learning_start:
  value: 2000
max_episode_steps:
  value: 1000
model_type:
  value: medium
num_envs:
  value: 8
save_test:
  value: 1000
tau:
  value: 1
total_time_steps:
  value: 100000
train_frequency:
  value: 50
update_target_frequency:
  value: 500
use_per:
  value: false
wandb_log:
  value: true
