wandb_version: 1

algorithm:
  value: DQN
alpha:
  value: 0.0007118798524776726
batch_size:
  value: 512
buffer_size:
  value: 10000
env:
  value: CartPole-v1
epsilon:
  value: 0.977700277948881
gamma:
  value: 0.9404070044156708
learning_start:
  value: 20000
max_episode_steps:
  value: 1000
model_type:
  value: medium
num_envs:
  value: 8
save_test:
  value: 1000
tau:
  value: 1
total_time_steps:
  value: 1000000
train_frequency:
  value: 20
update_target_frequency:
  value: 500
use_per:
  value: false
wandb_log:
  value: true
